### PR TITLE
Db abstraction

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by frett** [comment]
@wrandall22 @mattfred 

I've found that Dao classes got to be very repetitive to write in Android for the various queries & object serialization/deserialization. So, I implemented a framework modeled in part from JPA that allows you to mostly just model the structure of your tables and it currently provides most of the methods necessary for CRUD & querying of the data.

I broke the pull request out into a sequence of commits documenting the switch over for the TrainingDao. Once @mattfred is finished with his training branch & it is merged. I can rebase this branch and tweak as necessary to get this to merge in.

**Comment by frett** [comment]
I left your pre-existing methods in place and just have them reference the underlying methods as necessary to keep it from breaking usage elsewhere, long term code can be updated to make use of getCursor, find, get, updateOrInsert, & delete directly and the legacy wrappers can go away.

**Comment by wrandall22** [comment]
I added some things for the Ministry side of things.  I don't know if I can use the library to do the recursive stuff for associated ministries, though.

**Comment by frett** [comment]
I'll poke around with this some more this evening, don't view this as a critical component for the code at this time :)

**Comment by frett** [comment]
@wrandall22 I updated it with support for AssociatedMinistry.

I solved the issue by separating the processing of sub ministries from the mapping of the parent AssociatedMinistry object. So there are still wrapper methods that populate the objects, but most of the logic is left to the common AbstractDao.

**Comment by wrandall22** [comment]
Cool, thanks!

**Comment by frett** [comment]
I rebased off of the current master

**Comment by mattfred** [comment]
Looks good to me

**Comment by frett** [comment]
still want to do some more work on it, I was waiting for the rest of the training code to finish that up :) I'll probably do that work tonight and have it ready for review & merging in the morning.

**Comment by mattfred** [comment]
Ok sounds good

**Comment by frett** [comment]
@wrandall22 @mattfred this should be good to review now

**Comment by wrandall22** [comment]
Looks good to me.

**Comment by mattfred** [comment]
Looks fine to me as well. Thanks

**Comment by frett** [comment]
alright, I'll merge it :)

**Pull request merged**
