### PR TITLE
Ticket token update

### PR DESCRIPTION
**Pull request by mattfred**

### CODE REVIEW

**Comment by mattfred** [comment]
@wrandall22

**Comment by wrandall22** [comment]
Looks good to me. As Daniel said, we could put the Key client id in build.gradle and use `BuildConfig.THEKEY_CLIENTID` as they do in the gma app.

**Comment by mattfred** [comment]
the key client id has moved to gradle. Ready for me to merge Bill?

**Comment by wrandall22** [comment]
looks good to me

**Pull request merged**
