### PR TITLE
Measurements

### PR DESCRIPTION
**Pull request by wrandall22**
Here's the first run at the Measurements (LMI) page.

### CODE REVIEW

**Comment by wrandall22** [comment]
@mattfred

**Comment by frett** [comment]
+1 to removing the iml files :)

**Comment by wrandall22** [comment]
Working on making this branch conform with dbAbstraction branch.

**Comment by wrandall22** [comment]
Rebased with current master (previous head = 8f25abcab7dda7f184700a248d94364eac07325f)

**Comment by mattfred** [comment]
I tried this out but I get a 401 from the API. Anyways, the code looks good.

**Comment by wrandall22** [comment]
Did you choose a ministry in Settings before going to the measurements page?

**Comment by mattfred** [comment]
oh no. I will try that

**Comment by mattfred** [comment]
There was a ministry selected, still 401

**Comment by wrandall22** [comment]
Did you select a ministry that you were blocked status? Did the MCC get chosen?  The branch I'm working on right now will set a default MCC on the main activity so it shouldn't be an issue in the future.

**Comment by mattfred** [comment]
I did select an MCC. I'll look at it with you tomorrow.

**Pull request merged**
