### PR TITLE
API session management

### PR DESCRIPTION
**Pull request by frett**
This branch utilizes a common API client framework that tries to abstract some of the repetitive raw connection tasks and session management away from the API being implemented.

### CODE REVIEW

**Comment by frett** [comment]
@wrandall22 @mattfred

I only updated a couple API methods so far to use the framework. This should make it easier to implement the rest of the API methods that are necessary and not have to worry about tracking the lifecycle of a session.

**Comment by wrandall22** [comment]
I notice that this branch is using a different version of the gto support library than the db branch is, which one should be used?

**Comment by frett** [comment]
I cut 0.4.1 with the db features before I made some tweaks for the api stuff. before we get to release I'll cut another release build and use that.

**Comment by frett** [comment]
so,
0.4.1 has all the db abstraction (only a few minor tweaks compared to 0.4.0)
0.4.2-SNAPSHOT is the current development state with a bunch of API abstraction work

**Comment by frett** [comment]
rebased off current master

**Comment by frett** [comment]
well, I suppose it helps if I actually attempt to run the code after writing it at 2am and not just make sure it's not throwing errors in Android Studio.

I just fixed some method/class visibility on the underlying gto-support module and added some missing TargetApi annotations.

**Comment by frett** [comment]
@wrandall22 @mattfred 

alright, I think all the kinks are worked out. Jon also added the necessary WWW-Authenticate headers to distinguish between session expired and unauthorized to this resource.

I was able to confirm that getAllMinistries successfully picked up a new session as needed.

**Comment by frett** [comment]
I'll get this rebased now that #23 and #24 got merged in

**Comment by frett** [comment]
@wrandall22 

rebased and added in a createAssignment API method

**Comment by frett** [comment]
rebased one more time :)

**Comment by wrandall22** [comment]
Looks good to me.

**Pull request merged**
