### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by mattfred**
@wrandall22

### CODE REVIEW

**Comment by wrandall22** [comment]
Seems to make sense to me.

**Comment by wrandall22** [comment]
So, we want it onStop and not onDestroy?  It gets instantiated onCreate, not onStart.

**Comment by wrandall22** [comment]
@mattfred

**Comment by frett** [comment]
I would match the callbacks, so onCreate & onDestroy or in my apps I use onResume & onPause

**Pull request merged**
