### PR TITLE
Training

### PR DESCRIPTION
**Pull request by mattfred**
@wrandall22 Here is the training branch which also does cookies. The training section is not fully implemented because it does not get completed training yet. However, the main training section is done, and since this makes the connection to the api work I figured I would go ahead a push it. I will create a new branch for completed training.

### CODE REVIEW

**Comment by mattfred** [comment]
Good call. Updated.

**Comment by wrandall22** [comment]
Looks good to me.

**Comment by mattfred** [comment]
One more update

**Comment by wrandall22** [comment]
I think this is better

**Pull request merged**
