### PR TITLE
update testing

### PR DESCRIPTION
**Pull request by mattfred**
- create UserDao test
- add logging to check for locked database

### CODE REVIEW

**Comment by mattfred** [comment]
@wrandall22 Here is some extra testing. I also added some logging because I am getting some issues with locked database.

**Comment by mattfred** [comment]
clean up has been added

**Comment by wrandall22** [comment]
Looks good to me. Has the logging helped at all so far?

**Comment by mattfred** [comment]
Not yet. However, the main issues I am having are in another branch. So when I merge it will give me a better idea. I am also getting a warning that the `SQLiteConnection` is leaking. I am hoping to fix that as well.

**Pull request merged**
