### PR TITLE
Correct the way connection to the api is made

### PR DESCRIPTION
**Pull request by mattfred**
- fetch/generate service url for GCM api
- retrieve a service ticket for the service url: String ticket = theKey.getTicket(serviceUrl)
- use service ticket to authenticate to GCM api, which returns a GCM session token
- use GCM session token to make api calls

### CODE REVIEW

**Comment by mattfred** [comment]
@wrandall22 This is working now :-)

**Comment by wrandall22** [comment]
Could you add some javadoc to explain the differences between TokenTask and TicketTask?

**Comment by mattfred** [comment]
let me know if that is sufficient.

**Comment by wrandall22** [comment]
Yeah, looks good. Thanks!

**Pull request merged**
