### PR TITLE
Join ministry

### PR DESCRIPTION
**Pull request by wrandall22**
This PR adds the Join Ministry page.  Currently it is using dummy values when the server returns a 401 status code so we can test it properly.  This also saves/loads the initial assignments brought back from the initial token request from the key and populates the settings options with that.  We may only want the parent ministries to show up in Settings, I'm not sure.

### CODE REVIEW

**Comment by wrandall22** [comment]
@mattfred

**Comment by wrandall22** [comment]
Moved the http logic into GmaApiClient

**Comment by mattfred** [comment]
I think this looks good bill.

**Comment by mattfred** [comment]
once this is merged i'll send you a PR with the cookie update and that will get the api working.

**Comment by wrandall22** [comment]
Ok, I have implemented the save/load all ministries to/from database piece.

**Pull request merged**
