### PR TITLE
Add charts

### PR DESCRIPTION
**Pull request by wrandall22**
This PR implements the Measurement Details page.  It currently rides on top of #23 so that one should be reviewed first.  This PR actually starts on commit f4a46c52d490280b4349032e173afcc386996645

### CODE REVIEW

**Comment by wrandall22** [comment]
@mattfred to be reviewed after #23

**Comment by wrandall22** [comment]
Rebased with newly rebased measurements PR. Previous head: f4a46c52d490280b4349032e173afcc386996645

**Comment by wrandall22** [comment]
This PR really starts on commit 2ab93b59fc3baa53e74e895a903054022b486b71

**Comment by mattfred** [comment]
This looks good

**Pull request merged**
