### PR TITLE
Actually create new assignments

### PR DESCRIPTION
**Pull request by frett**
This PR will issue the createAssignment API request to the backend and handle the response. It is based off PR #25 and should be reviewed/merged after that one

### CODE REVIEW

**Comment by frett** [comment]
@wrandall22 @mattfred

**Comment by wrandall22** [comment]
I'm thinking that, now that we're using _id, the field `id` in assignments should maybe be changed to `assignment_id` or something, to not get confused with the base `_id`.

**Comment by frett** [comment]
I setup the transparent _id to be behind COLUMN_ROWID for tables that don't have a suitable natural _id column. The intention there was that this internal implementation detail should have very little effect elsewhere, and everything else could continue to treat the assignment uuid as the assignment id.

I also was going to add in an abstract findByRowId(Class, long) method to the AbstractDao that will lookup based on the rowid when needed, but I haven't had need yet so I haven't committed the code.

All that said, I'm fine going either way with the id field if there is the desire. The nice thing about everything going through the contract is that we can easily find and change all references to the field.

**Comment by wrandall22** [comment]
I'm fine with it going in the contract, I was just noting the fact that this table has both an `_id` column and an `id` column, and that might be confusing.  I was thinking perhaps `id` could be renamed is all, unless there is something special about it being named that specifically?

**Comment by frett** [comment]
good point, I'll get that updated.

**Comment by frett** [comment]
@wrandall22 

updated

**Comment by wrandall22** [comment]
Looks good to me

**Pull request merged**
